C

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,37 +1,68 @@
-name: Build and Run Kotlin in Java
+name: Java CI
 
 on:
   push:
     branches:
-      - javac_
-  pull_request:
-    branches:
-      - javac_
+      - javac_  # Adjust the branch name as needed
 
 jobs:
   build:
     runs-on: ubuntu-latest
 
     steps:
-      - name: Check out code
-        uses: actions/checkout@v2
+    - name: Checkout repository
+      uses: actions/checkout@v2
 
-      - name: Set up JDK 21
-        uses: actions/setup-java@v2
-        with:
-          java-version: '21'
-          distribution: 'temurin' # or 'adopt' for AdoptOpenJDK
+    - name: Set up JDK 21
+      uses: actions/setup-java@v2
+      with:
+        java-version: '21'
+        distribution: 'temurin'
+        java-package: 'jdk'
+        architecture: 'x64'
+        check-latest: false
+        overwrite-settings: true
+        job-status: 'success'
 
-      - name: Set up Kotlin
-        run: |
-          curl -s https://get.sdkman.io | bash
-          source "$HOME/.sdkman/bin/sdkman-init.sh"
-          sdk install kotlin
+    - name: Compile and Run Java Files
+      run: |
+        #!/bin/bash
+        # Compile all Java files
+        cd execute && javac *.java
+        # Check if compilation was successful
+        if [ $? -eq 0 ]; then
+            # Run each Java file in sequence
+            for file in *.java; do
+                # Get the base name of the file (without .java)
+                class_name="${file%.java}"
+                echo "Class $class_name..."
+                java "$class_name"
+            done
+        else
+            echo "Compilation failed."
+            exit 1
+        fi
+####################################################################################
 
-      - name: Compile Java and Kotlin
-        run: |
-          mvn clean compile
+# for Java 17
 
-      - name: Run Java Application
-        run: |
-          mvn exec:java -Dexec.mainClass="com.example.KotlinInJava" # Change to your main class
+    # - name: Set up JDK 17
+    #   uses: actions/setup-java@v2
+    #   with:
+    #     java-version: '17'
+    #     distribution: 'temurin'
+    #     java-package: 'jdk'
+    #     architecture: 'x64'
+    #     check-latest: false
+    #     overwrite-settings: true
+    #     job-status: 'success'
+
+    # - name: Compile Java File
+    #   run: |
+    #     javac execute/_50A_py.java
+
+    # - name: Run Java File
+    #   run: |
+    #     java -cp execute _50A_py
+
+####################################################################################
