C

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -13,6 +13,9 @@ jobs:
     - name: Checkout repository
       uses: actions/checkout@v2
 
+    - name: Install C++ Compiler
+      run: sudo apt-get install g++
+
     - name: Set up JDK 21
       uses: actions/setup-java@v2
       with:
@@ -29,6 +32,25 @@ jobs:
         #!/bin/bash
         # Compile all Java files
         cd execute && javac *.java
+        # Check if compilation was successful
+        if [ $? -eq 0 ]; then
+            # Run each Java file in sequence
+            for file in *.java; do
+                # Get the base name of the file (without .java)
+                class_name="${file%.java}"
+                echo "Class $class_name..."
+                java "$class_name"
+            done
+        else
+            echo "Compilation failed."
+            exit 1
+        fi
+
+    - name: Compile and Run Java Files 1
+      run: |
+        #!/bin/bash
+        # Compile all Java files
+        cd execute1 && javac *.java
         # Check if compilation was successful
         if [ $? -eq 0 ]; then
             # Run each Java file in sequence
