C

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -6,7 +6,7 @@ on:
       - main
 
 jobs:
-  build:
+  build-ubuntu:
     runs-on: ubuntu-latest
 
     steps:
@@ -39,58 +39,55 @@ jobs:
       - name: Run script
         run: npm run pystart
 
-      - name: List Foundation Framework Headers
-        run: |
-          #!/bin/bash
 
-          # Array of potential paths to check for Foundation.h
-          search_paths=(
-              "/usr/include/GNUstep/Foundation/Foundation.h"
-              "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h"
-              "/usr/local/include/Foundation/Foundation.h"
-              "/usr/include/Foundation/Foundation.h"
-          )
-
-          # Flag to track if the file was found
-          found=false
-
-          # Check each path
-          for path in "${search_paths[@]}"; do
-              if [[ -f "$path" ]]; then
-                  echo "Found Foundation.h at: $path"
-                  found=true
-                  break
-              fi
-          done
-
-          # If not found, print a message
-          if ! $found; then
-              echo "Foundation.h not found in the specified paths."
-          fi
-
-
-      - name: Compile and run Objective-C++ code
-        run: |
-          # Create the Objective-C++ source file
-          echo '#import </Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h>
-
-          int main(int argc, const char * argv[]) {
-              @autoreleasepool {
-                  NSLog(@"Hello from Objective-C++ on GitHub Actions from here!");
-              }
-              return 0;
-          }' > hello.mm
-
-          # Compile the source file
-          clang++ -std=c++11 -framework /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/Foundation.framework -o hello hello.mm
-
-          # Run the compiled executable
-          ./hello
-      
-
-      # - name: Run script 50 times
+      # - name: Compile and run Objective-C++ code
       #   run: |
-      #     for i in $(seq 1 50); do
-      #       echo "Run #$i"
-      #       npm run pystart  # Replace with the path to your script
-      #     done
+      #     # Create the Objective-C++ source file
+      #     echo '#import </Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h>
+
+      #     int main(int argc, const char * argv[]) {
+      #         @autoreleasepool {
+      #             NSLog(@"Hello from Objective-C++ on GitHub Actions from here!");
+      #         }
+      #         return 0;
+      #     }' > hello.mm
+
+      #     # Compile the source file
+      #     clang++ -std=c++11 -framework /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/Foundation.framework -o hello hello.mm
+
+      #     # Run the compiled executable
+      #     ./hello
+
+  build-macos:
+    runs-on: macos-latest
+
+    steps:
+
+    - name: List Foundation Framework Headers
+      run: |
+        #!/bin/bash
+
+        # Array of potential paths to check for Foundation.h
+        search_paths=(
+            "/usr/include/GNUstep/Foundation/Foundation.h"
+            "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h"
+            "/usr/local/include/Foundation/Foundation.h"
+            "/usr/include/Foundation/Foundation.h"
+        )
+
+        # Flag to track if the file was found
+        found=false
+
+        # Check each path
+        for path in "${search_paths[@]}"; do
+            if [[ -f "$path" ]]; then
+                echo "Found Foundation.h at: $path"
+                found=true
+                break
+            fi
+        done
+
+        # If not found, print a message
+        if ! $found; then
+            echo "Foundation.h not found in the specified paths."
+        fi
